### ISSUE TITLE
Calculate Meal By Class

### ISSUE THREAD

**Issue by dhnugroho** [npratama/Contrast#19]
- Bu Nana dan Pak Syahriel di periode bistrip dan kelas yang sama tetapi amount meal nya beda
- Pak Nurhadi kelas 7 tapi meal untuk 2 hari 225ribu, bukannya harusnya 450ribu (225ribu/hari)

**Comment by dhnugroho** [comment]
ini karena dia participant BTA1235 & BTA1236 , calculate meal blm terhitung by duration msh - 1 days

**Comment by npratama** [comment]
Problem occurred due the person are listed as participant. Fix sp of participant
